spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/intens-java
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.jpa.open-in-view=true

springdoc.api-docs.enabled=false